/**
 * Memory System — CLAUDE.md + MEMORY.md
 *
 * Hierarchy:
 * 1. ~/.claude/CLAUDE.md   — global user preferences
 * 2. <project>/CLAUDE.md   — project-level instructions
 * 3. <project>/MEMORY.md   — auto-written session memories
 *
 * Limits mirror Claude Code exactly.
 */

import fs from 'fs/promises';
import { resolve, join, dirname } from 'path';
import { homedir } from 'os';

// ─── Constants ────────────────────────────────────────────────────────────────

export const MAX_MEMORY_LINES  = 200;
export const MAX_MEMORY_BYTES  = 25_000;
export const MEMORY_FILENAME   = 'MEMORY.md';
export const CLAUDE_FILENAME   = 'CLAUDE.md';
export const GLOBAL_CONFIG_DIR = join(homedir(), '.claude');

// ─── Loader ───────────────────────────────────────────────────────────────────

/**
 * Truncate memory content with warning message if over limits.
 * Same logic as Claude Code's truncateEntrypointContent().
 */
function truncateMemory(raw, filename) {
  const trimmed = raw.trim();
  const lines   = trimmed.split('\n');
  const lineCount = lines.length;
  const byteCount = Buffer.byteLength(trimmed);

  const overLines = lineCount > MAX_MEMORY_LINES;
  const overBytes = byteCount > MAX_MEMORY_BYTES;

  if (!overLines && !overBytes) return trimmed;

  let truncated = overLines
    ? lines.slice(0, MAX_MEMORY_LINES).join('\n')
    : trimmed;

  if (Buffer.byteLength(truncated) > MAX_MEMORY_BYTES) {
    const cutAt = truncated.lastIndexOf('\n', MAX_MEMORY_BYTES);
    truncated   = truncated.slice(0, cutAt > 0 ? cutAt : MAX_MEMORY_BYTES);
  }

  const reason = overLines && overBytes
    ? `${lineCount} lines and ${byteCount} bytes`
    : overLines
    ? `${lineCount} lines (limit: ${MAX_MEMORY_LINES})`
    : `${byteCount} bytes (limit: ${MAX_MEMORY_BYTES})`;

  return (
    truncated +
    `\n\n> WARNING: ${filename} is ${reason}. Only part was loaded. ` +
    `Keep entries under ~200 chars each.`
  );
}

async function readFileOptional(path) {
  try {
    return await fs.readFile(path, 'utf8');
  } catch {
    return null;
  }
}

/**
 * Load all memory files and return as a single prompt string.
 * Called once per session start, results injected into system prompt.
 */
export async function loadMemoryPrompt(cwd) {
  const parts = [];

  // 1. Global ~/.claude/CLAUDE.md
  const globalClaude = await readFileOptional(join(GLOBAL_CONFIG_DIR, CLAUDE_FILENAME));
  if (globalClaude) {
    parts.push({
      source: `~/.claude/${CLAUDE_FILENAME}`,
      content: truncateMemory(globalClaude, CLAUDE_FILENAME),
    });
  }

  // 2. Project CLAUDE.md (check multiple locations)
  for (const loc of [join(cwd, CLAUDE_FILENAME), join(cwd, '.claude', CLAUDE_FILENAME)]) {
    const projectClaude = await readFileOptional(loc);
    if (projectClaude) {
      parts.push({
        source: loc.replace(homedir(), '~'),
        content: truncateMemory(projectClaude, CLAUDE_FILENAME),
      });
      break; // only first found
    }
  }

  // 3. Project MEMORY.md
  for (const loc of [join(cwd, MEMORY_FILENAME), join(cwd, '.claude', MEMORY_FILENAME)]) {
    const memory = await readFileOptional(loc);
    if (memory) {
      const mtime = await fs.stat(loc).then(s => s.mtime).catch(() => null);
      const age   = mtime ? formatAge(mtime) : 'unknown age';
      parts.push({
        source: loc.replace(homedir(), '~'),
        content: truncateMemory(memory, MEMORY_FILENAME),
        note: `(last updated: ${age})`,
      });
      break;
    }
  }

  if (!parts.length) return null;

  const sections = parts.map(p =>
    `## Memory: ${p.source}${p.note ? '  ' + p.note : ''}\n\n${p.content}`
  );

  return (
    `# Persistent Memory\n\n` +
    `The following was loaded from memory files. ` +
    `Trust this context but verify file contents if needed.\n\n` +
    sections.join('\n\n---\n\n')
  );
}

// ─── Memory Writer ────────────────────────────────────────────────────────────

/**
 * Write or append to MEMORY.md.
 * Called by the /remember command or the save_memory tool.
 */
export async function appendMemory(cwd, content) {
  const memPath = join(cwd, MEMORY_FILENAME);
  const timestamp = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

  const entry = `\n## ${timestamp}\n\n${content.trim()}\n`;

  const existing = await readFileOptional(memPath);
  const newContent = (existing || `# Session Memory\n\nAuto-generated by RXS Code.\n`) + entry;

  await fs.writeFile(memPath, newContent, 'utf8');
  return memPath;
}

/**
 * Read current MEMORY.md content (raw).
 */
export async function readMemory(cwd) {
  const memPath = join(cwd, MEMORY_FILENAME);
  return await readFileOptional(memPath);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatAge(date) {
  const ms   = Date.now() - date.getTime();
  const mins = Math.floor(ms / 60_000);
  const hrs  = Math.floor(ms / 3_600_000);
  const days = Math.floor(ms / 86_400_000);
  if (days  > 0) return `${days} day${days  > 1 ? 's' : ''} ago`;
  if (hrs   > 0) return `${hrs} hr${hrs   > 1 ? 's' : ''} ago`;
  if (mins  > 0) return `${mins} min ago`;
  return 'just now';
}
